"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { questionnaireApi, type Response } from "@/lib/questionnaires";

export default function ResponsesBoard({ id }: { id: string }) {
  const [responses, setResponses] = useState<Response[]>([]); const [view, setView] = useState<"grid" | "kanban">("grid"); const [error, setError] = useState("");
  useEffect(() => { questionnaireApi.responses(id).then(setResponses).catch((e: Error) => setError(e.message)); }, [id]);
  const columns = useMemo(() => Array.from(new Set(responses.flatMap((r) => Object.keys(r.answers ?? {})))), [responses]);
  if (error) return <div className="rounded-xl border border-error-200 bg-error-50 p-5 text-error-700">{error}</div>;
  const statuses = ["new", "in_progress", "completed"];
  return <div><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link href={`/questionnaires/${id}`} className="text-sm text-brand-500">← بازگشت به پرسشنامه</Link><h1 className="mt-2 text-2xl font-bold text-gray-800 dark:text-white/90">پاسخ‌ها</h1></div><div className="rounded-lg bg-gray-100 p-1 dark:bg-gray-800"><button onClick={() => setView("grid")} className={`rounded-md px-3 py-2 text-sm ${view === "grid" ? "bg-white shadow-sm dark:bg-gray-700" : "text-gray-500"}`}>Grid</button><button onClick={() => setView("kanban")} className={`rounded-md px-3 py-2 text-sm ${view === "kanban" ? "bg-white shadow-sm dark:bg-gray-700" : "text-gray-500"}`}>Kanban</button></div></div>{!responses.length ? <div className="rounded-xl border border-dashed border-gray-300 p-10 text-center text-gray-500">هنوز پاسخی ثبت نشده است.</div> : view === "grid" ? <div className="overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-800"><table className="min-w-full text-right text-sm"><thead className="bg-gray-50 text-gray-500 dark:bg-gray-900"><tr><th className="p-4">شناسه</th>{columns.map((c) => <th key={c} className="p-4">{c}</th>)}<th className="p-4">وضعیت</th></tr></thead><tbody>{responses.map((r) => <tr key={r.id} className="border-t border-gray-100 dark:border-gray-800"><td className="p-4">#{r.id}</td>{columns.map((c) => <td key={c} className="max-w-48 truncate p-4">{Array.isArray(r.answers?.[c]) ? (r.answers[c] as string[]).join(", ") : String(r.answers?.[c] ?? "—")}</td>)}<td className="p-4">{r.status ?? "new"}</td></tr>)}</tbody></table></div> : <div className="grid gap-4 lg:grid-cols-3">{statuses.map((status) => <section key={status} className="rounded-xl bg-gray-100 p-4 dark:bg-gray-900"><h2 className="mb-3 font-semibold capitalize text-gray-700 dark:text-white/90">{status.replace("_", " ")}</h2><div className="space-y-3">{responses.filter((r) => (r.status ?? "new") === status).map((r) => <article key={r.id} className="rounded-lg bg-white p-4 shadow-theme-xs dark:bg-gray-800"><p className="font-medium">پاسخ #{r.id}</p><p className="mt-1 text-xs text-gray-500">{r.respondent?.name ?? r.submitted_at ?? r.created_at ?? "بدون تاریخ"}</p><p className="mt-3 line-clamp-3 text-sm text-gray-600 dark:text-gray-300">{Object.values(r.answers ?? {}).map(String).join(" · ")}</p></article>)}</div></section>)}</div>}</div>;
}
