"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { clinicAdminApi, type AdminQuestionnaire } from "@/lib/clinic-admin";
import ClinicQuestionTextEditor from "@/components/clinic-admin/ClinicQuestionTextEditor";

export default function ClinicFormEditor({ id }: { id: string }) {
  const [form, setForm] = useState<AdminQuestionnaire | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState("");
  useEffect(() => { clinicAdminApi.form(id).then(setForm).catch((e) => setError(e instanceof Error ? e.message : "Could not load this form.")); }, [id]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!form) return; setSaving(true); try { setForm(await clinicAdminApi.updateForm(id, form)); setSaved("Form changes have been saved."); } catch (e) { setError(e instanceof Error ? e.message : "Could not save form."); } finally { setSaving(false); } }
  if (error) return <div className="rounded-xl border border-error-200 bg-error-50 p-4 text-sm text-error-700">{error}</div>;
  if (!form) return <p className="text-sm text-gray-500">Loading form…</p>;
  return <form onSubmit={save} className="space-y-6"><section className="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-white/[0.03]"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-brand-600">Clinic form</p><h1 className="mt-1 text-2xl font-bold text-gray-900 dark:text-white">Edit form</h1></div><Link href="/admin/forms" className="text-sm font-semibold text-gray-600 dark:text-gray-300">Back to forms</Link></div><div className="mt-6 grid gap-5"><label className="text-sm font-medium text-gray-700 dark:text-gray-300">Form title<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="mt-2 h-11 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white" /></label><label className="text-sm font-medium text-gray-700 dark:text-gray-300">Description<textarea value={form.description ?? ""} onChange={(event) => setForm({ ...form, description: event.target.value })} rows={3} className="mt-2 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white" /></label><label className="text-sm font-medium text-gray-700 dark:text-gray-300">Status<select value={form.status ?? "draft"} onChange={(event) => setForm({ ...form, status: event.target.value })} className="mt-2 h-11 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label></div></section><section className="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-white/[0.03]"><h2 className="text-lg font-bold text-gray-900 dark:text-white">Question text and help</h2><p className="mt-1 text-sm text-gray-500">Changes are saved per question, so they can be reviewed independently.</p><div className="mt-5 space-y-4">{form.questions?.map((question) => <ClinicQuestionTextEditor key={question.id} formId={id} question={question} />) ?? <p className="text-sm text-gray-500">No editable questions were returned.</p>}</div></section><div className="flex items-center justify-end gap-3"><p className="text-sm text-success-600">{saved}</p><button disabled={saving} className="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving ? "Saving…" : "Save form"}</button></div></form>;
}
